#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	// string table definitions
	IDS_REAWOTE_PBR_CONVERTER	= 20000,

  	IDS_DIALOG_BROWSE,
  	IDS_DIALOG_TEXTURE_FOLDER,
	IDS_DIALOG_MAIN_GROUP,
	IDS_DIALOG_SCROLL_GROUP,
	IDS_DIALOG_SCROLL_GROUP_TWO,
	IDS_DIALOG_SECONDARY_GROUP,
	IDS_DIALOG_LIST_CHECKBOX,
	IDS_DIALOG_FOLDER_LIST,
  	IDS_DIALOG_INCLUDE_AO,
  	IDS_DIALOG_INCLUDE_DISPLACEMENT,
  	IDS_DIALOG_USE_16_BIT_MAPS,
	IDS_DIALOG_LOAD,

	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__