#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	// string table definitions
	IDS_REAWOTE_PBR_CONVERTER	= 20000,

  	IDS_DIALOG_BROWSE,
  	IDS_DIALOG_TEXTURE_FOLDER,
	IDS_DIALOG_MAIN_GROUP,
	IDS_DIALOG_FOLDER_GROUP,
	IDS_DIALOG_FOLDER_TEXT,
	IDS_DIALOG_FOLDER_BUTTON,
	IDS_DIALOG_FOLDER_LIST,
	IDS_DIALOG_GROUP_DROPBOXES,
	IDS_DIALOG_DROPBOX_BUTTON1,
	IDS_DIALOG_DROPBOX_MAIN,
	IDS_DIALOG_DROPBOX_BUTTON2,
	IDS_DIALOG_GROUP2_DROPBOXES,
	IDS_DIALOG_TEXT2_DROPBOX,
	IDS_DIALOG_DROPBOX_MAIN3,
	IDS_DIALOG_GROUP3_DROPBOXES,
	IDS_DIALOG_TEXT_DROPBOX,
	IDS_DIALOG_DROPBOX_MAIN2,
	IDS_DIALOG_LIST_BUTTON,
	IDS_DIALOG_ADD_TO_LIST_BUTTON,
	IDS_DIALOG_SELECT_ALL_BUTTON,
	IDS_DIALOG_SCROLL_GROUP,

	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__